### ISSUE TITLE
No example data?

### ISSUE THREAD

**Issue by JohnsonBrent** [manindersingh120996/Custom-word-Embedding#1]
Thanks for your example script and article.  It'd be nice to see the example data referenced in the python script as `preprocessed_text_file.txt`. Maybe as a simple download along with the code?  Without that file. the script doesn't run as a stand-alone example.

**Comment by manindersingh120996** [comment]
[preprocessed_text_file.txt](https://github.com/user-attachments/files/16922045/preprocessed_text_file.txt)


Hi, 
Provided is the sample file around medical data consisting of 50 examples, which can be used for the purpose to check the code and latter can be replaced with your own data.

Also, these are just the sample data, just to check the code working.

Thank You

**Comment by manindersingh120996** [comment]
Hi, 
Provided is the sample file around medical data consisting of 50 examples, which can be used for the purpose.
You might need to further process the file to remove the numerics in the beginning of the sentences.
Thank You
